<?php

namespace ContainerFQgQBRE;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XHSC9h4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.XHSC9h4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XHSC9h4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\ArtistController::index' => ['privates', '.service_locator.h1Klj3y', 'get_ServiceLocator_H1Klj3yService', true],
            'App\\Controller\\ArtistsController::index' => ['privates', '.service_locator.h1Klj3y', 'get_ServiceLocator_H1Klj3yService', true],
            'App\\Controller\\RecordController::index' => ['privates', '.service_locator.DMC20ZE', 'get_ServiceLocator_DMC20ZEService', true],
            'App\\Controller\\RecordsController::index' => ['privates', '.service_locator.DMC20ZE', 'get_ServiceLocator_DMC20ZEService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel::terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
            'App\\Controller\\ArtistController:index' => ['privates', '.service_locator.h1Klj3y', 'get_ServiceLocator_H1Klj3yService', true],
            'App\\Controller\\ArtistsController:index' => ['privates', '.service_locator.h1Klj3y', 'get_ServiceLocator_H1Klj3yService', true],
            'App\\Controller\\RecordController:index' => ['privates', '.service_locator.DMC20ZE', 'get_ServiceLocator_DMC20ZEService', true],
            'App\\Controller\\RecordsController:index' => ['privates', '.service_locator.DMC20ZE', 'get_ServiceLocator_DMC20ZEService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.xUrKPVU', 'get_ServiceLocator_XUrKPVUService', true],
            'kernel:terminate' => ['privates', '.service_locator.bRdave9', 'get_ServiceLocator_BRdave9Service', true],
        ], [
            'App\\Controller\\ArtistController::index' => '?',
            'App\\Controller\\ArtistsController::index' => '?',
            'App\\Controller\\RecordController::index' => '?',
            'App\\Controller\\RecordsController::index' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\ArtistController:index' => '?',
            'App\\Controller\\ArtistsController:index' => '?',
            'App\\Controller\\RecordController:index' => '?',
            'App\\Controller\\RecordsController:index' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
