<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFQgQBRE\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFQgQBRE/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFQgQBRE.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFQgQBRE\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFQgQBRE\App_KernelDevDebugContainer([
    'container.build_hash' => 'FQgQBRE',
    'container.build_id' => '75ce1fa2',
    'container.build_time' => 1652261079,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFQgQBRE');
